### ISSUE TITLE
Title of the homepage should be fetched

### ISSUE THREAD

**Issue by deniak** [miccycn/A-Simple-NodeJS-Application#1]
The form shouldn't have a "homepage title" `<input>`. The title should be fetched directly from the url.

**Comment by miccycn** [comment]
Thank you for you reminding, I have fixed this problem, and update a new version.

**Comment by miccycn** [comment]
> The form shouldn't have a "homepage title" `<input>`. The title should be fetched directly from the url.
Thank you for you reminding, I have fixed this problem, and updated a new version.

**Comment by miccycn** [comment]
> The form shouldn't have a "homepage title" `<input>`. The title should be fetched directly from the url.

Thank you for you reminding, I have fixed this problem, and updated a new version.

**Comment by deniak** [comment]
@miccycn Thank you for patching the repository. That's what we had in mind :+1:
